Инициализация проект
PraktikumSeoulDevTeam/castleofghosts pull request #1
Opened 2020-10-29 13:00 UTC by FellonOne

Сконфигурировал проект на основе webpack + babel + typescript + react
Добавил все лоадеры в webpack.config.js
Добавил конфиг для typescript

2020-10-29 14:28 UTC, kdeit commented on package.json
> +  "author": "Артем Мозговой, Дима Кузнецов, Никита Иванов",
Может будем придерживаться english?

2020-10-29 14:28 UTC, kdeit commented on package.json
> +    "react": "^17.0.1",
А давайте зависимости лочить (предложение)

2020-10-29 14:44 UTC, art4vm commented on package.json
> +    "react": "^17.0.1",
Как по мне, так изменение минорной версии зависимости чаще всего не критично. А еще, можно lock файл коммитить.

2020-10-29 15:10 UTC, art4vm requested changes

2020-10-29 15:10 UTC, art4vm commented on package.json
> +  "main": "./dist/index.html",
main обычно это js файл. Но тк данная программа не предполагает импортироваться в качестве зависимости, данный параметр не имеет смысла.

2020-10-29 15:10 UTC, art4vm commented on tsconfig.json
> +    "typeRoots": ["typings/**/*.d.ts", "node_modules/@types"],
это можно удалить, по умолчанию node_modules/@types и так включен, а typings у нас скорей всего не будет

2020-10-29 15:10 UTC, art4vm commented on tsconfig.json
> +    "lib": [
в принципе Lib не нужен, тк и dom и es2017 в случае esnext уже будет включен по умолчанию

2020-10-29 15:10 UTC, art4vm commented on tsconfig.json
> +    "baseUrl": ".",
./src. А вообще, я бы предложил перенести в каталог ./app/src, тк у нас потом еще сервер появится, и возможно удобно было бы его поместить в каталог ./server/src

2020-10-29 15:10 UTC, art4vm commented on tsconfig.json
> +    "target": "es5",
думаю можно поменять на es2015

2020-10-29 15:10 UTC, art4vm commented on package.json
> +    "start": "webpack serve --mode development --watch",
тут не надо webpack-dev-server использовать? Или тогда уж webpack-cli

2020-10-29 16:07 UTC, FellonOne commented on package.json
> +  "author": "Артем Мозговой, Дима Кузнецов, Никита Иванов",
Да, согласен. Нужны будут ваши именна на латинице

2020-10-29 16:08 UTC, FellonOne commented on tsconfig.json
> +    "typeRoots": ["typings/**/*.d.ts", "node_modules/@types"],
Да, тогда наверное удалю

2020-10-29 16:08 UTC, FellonOne commented on package.json
> +    "start": "webpack serve --mode development --watch",
Это и есть запуск webpack-dev-server, сокращенная версия

2020-10-29 16:11 UTC, FellonOne commented on tsconfig.json
> +    "baseUrl": ".",
Да, согласен
app/src
server/src
Но конфиги тогда смешаются. У бекенда будет свой конфиг на TS. Плюс мб мы позже расиширм конфиг для вебпака, разделив его на 2 части -> dev и prod версии
В теории, пока с папками можно не париться. А в 3-ем спринте перенести. Либо сейчас это сделать

2020-10-30 12:42 UTC, FellonOne commented
Нужны ли какие-то правки или задачу можно считать готовой?

2020-10-30 13:19 UTC, art4vm commented on server/package.json
> +{
Думаю отдельный package.json не нужен. У нас по сути будет 1 приложение с 2 модулями, сервер и клиент. Дублировать зависимости нет смысла

2020-10-30 14:51 UTC, kdeit commented on server/package.json
> +{
А я бы разделял, как Никита. Бек сейчас сделаем «по-быстрому». Мало-ли потом перепишем под нагрузку в 100 млн пользователей. Независимость наше всё.

2020-10-30 17:36 UTC, art4vm commented on server/package.json
> +{
А как это связано с нагрузкой? Если делать 2 независимых приложения, то и репозитории нужно разделять. 2 структуры с зависимосями руздует проект. В частонсти могут возникнуть проблемы с CI из за нестандартного расположения package.json и из за размера docker контейнера

2020-10-31 06:04 UTC, FellonOne commented on server/package.json
> +{
Ну, два проекта в одном репозитории могут существовать, это сейчас называется - монорепозиторием (насколько знаю, хорошо практикуется в Яндексе/Гугле и других компаниях). Но я убрал разделения. Их можно будет в будущем вернуть, там делов на пару минут. Пока не будем сильно на этом останавливаться

2020-10-31 11:57 UTC, art4vm approved these changes, later dismissed
Ok

2020-10-31 14:28 UTC, Jarith commented on package.json
> +    "react": "^17.0.1",
К сожалению не все и не всегда строго соблюдают semver и были случаи, когда минорный релиз включал в себя breaking changes. Поэтому лучше все же фиксировать

2020-10-31 14:29 UTC, Jarith approved these changes, later dismissed

2020-11-01 09:51 UTC, kdeit submitted a review, later dismissed

2020-11-01 10:09 UTC, Jarith approved these changes

2020-11-01 10:44 UTC, kdeit approved these changes

2020-11-01 10:44 UTC, art4vm approved these changes

2020-11-01 10:44 UTC, merged

2020-11-01 15:00 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cтруктура проекта](https://trello.com/c/7Tp3r7te/19-c%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0)