feature/authorization-registration-forms
PraktikumSeoulDevTeam/castleofghosts pull request #17
Opened 2020-11-19 16:36 UTC by FellonOne

add Formik library;

2020-11-19 16:38 UTC, Jarith approved these changes, later dismissed

2020-11-19 18:20 UTC, art4vm requested changes

2020-11-19 18:20 UTC, art4vm commented on package.json
> +    "@types/yup": "^0.29.9",
залочить

2020-11-19 18:20 UTC, art4vm commented on app/src/router/AppRouter/AppRouter.tsx
> +import {ErrorPage, GamePage, Authorization, Registration, WelcomePage} from '../../pages';
Предлагаю названия страниц заканчивать на **Page**

2020-11-19 18:20 UTC, art4vm commented on app/src/components/formControl/FormControl.tsx
> +import React from 'react';
у тебя 2 fromControl каталога, 1 с маленькой буквы и 1 с большой

2020-11-19 18:20 UTC, art4vm commented on app/src/components/formControl/FormControl.tsx
> +import React from 'react';
Переименую все каталоги formControl, button и copyright

2020-11-19 18:20 UTC, art4vm commented on app/src/assets/scss/_authentication.scss
> +.authentication {
переименуй файл без _

2020-11-19 18:20 UTC, art4vm commented on app/src/components/AuthButton/AuthButton.tsx
> +import {Button} from '../button/Button';
поправь наименование каталога

2020-11-19 18:44 UTC, kdeit submitted a review, later dismissed

2020-11-19 18:44 UTC, kdeit commented on app/src/assets/scss/_authentication.scss
> +    color: white;
Тут лучше писать #ffffff вместо «white». Ходит легенда, что в некоторых браузерах white не прям белый и может быть разным.

2020-11-19 18:44 UTC, kdeit commented on app/src/assets/scss/_authentication.scss
> +    color: white;
И ниже там есть Red...

2020-11-19 18:44 UTC, kdeit commented on app/src/components/formControl/FormControl.scss
> +        color: indianred;
Лучше через переменные (как и всю цветовую гамму)

2020-11-19 18:51 UTC, art4vm commented on app/src/assets/scss/_authentication.scss
> +    color: white;
Если нет какой-то необходимости, нет смысла устанавливать color: white(или #fff), тк он установлен в body

2020-11-21 10:32 UTC, kdeit approved these changes, later dismissed

2020-11-21 10:34 UTC, art4vm requested changes
не поправил formControl и FormControl, судя по diff эти 2 каталога присутствуют одновременно со всем содержимым

2020-11-21 11:37 UTC, FellonOne commented
> не поправил formControl и FormControl, судя по diff эти 2 каталога присутствуют одновременно со всем содержимым

Нет, поправил, у меня локально только в одном экземпляре

2020-11-22 06:24 UTC, art4vm approved these changes, later dismissed

2020-11-22 07:20 UTC, art4vm reviewed
Хотел заметить, что сама форма с полями имеет вид, не такой как ожидается по дизайну. Это так и должно быть, или будет дорабатываться?

2020-11-22 07:57 UTC, art4vm approved these changes

2020-11-22 07:57 UTC, Jarith approved these changes

2020-11-22 07:57 UTC, merged