Компонент AuthButton заменен на ActionButton
PraktikumSeoulDevTeam/castleofghosts pull request #27
Opened 2020-11-24 16:06 UTC by art4vm

В кнопке предусмотрено 2 действия goback и logout
goback можно использовать на всех страницах, вместо явного указания маршрута, сейчас необходимость есть на странице leaderboard
logout предполагается использовать в меню

2020-11-26 13:56 UTC, FellonOne requested changes

2020-11-26 13:56 UTC, FellonOne commented on app/src/components/ActionButton/ActionButton.tsx
> +                const dispatch = useDispatch();
На колле договорились, что не будем использоваться useDispatch -> не консистентно. Либо везде useDispatch, либо везде HOC'ом через connect

2020-11-26 13:56 UTC, FellonOne commented on app/src/components/ActionButton/ActionButton.tsx
> +);
Кажется очень странным, что компонент ведет себя по разному. Прям слишком. Одна логика -> Logout
Другая логика -> редирект назад

Лучше оформить два HOC: withLogout и withRedirect
Туда вынести логику. И просто в нужных метсах навешивать на кнопку

2020-11-26 15:10 UTC, art4vm commented on app/src/components/ActionButton/ActionButton.tsx
> +);
В данном проекте много странностей, и эта не самая большая.
Целью данного компонента является избавление от необходимости выносить логику наружу.

> HOC: withLogout

откуда в HOC возьмется redux контекст? С таким же успехом можно удалить вообще компонент и навешивать нужные действия прямо в месте вызова Button.
Можно разделить на 2 компонента. Но не вижу в это какой-то выгоды

2020-11-26 15:10 UTC, art4vm commented on app/src/components/ActionButton/ActionButton.tsx
> +                const dispatch = useDispatch();
useDispatch можно использовать по требованию, а connect всегда добавляет свой контекст, даже если это не требуется.

2020-11-27 01:12 UTC, Jarith requested changes
Навигация и логин/логаут - разная логика, не стоит ее смешивать в одном компоненте. 

Предлагаю вернуть старую кнопку, а необходимость подобных рефакторингов обсуждать в чате или на созвонах

2020-11-27 01:12 UTC, jarith commented on app/src/components/ActionButton/ActionButton.tsx
> +                const dispatch = useDispatch();
Так мы и `connect` добавляем там, где нужно диспатчить экшены или прокинуть значения из стора.

Давайте все же придерживаться договоренностей. Иначе получится, что мы зря тратили время на обсуждение

2020-11-27 01:12 UTC, jarith commented on app/src/components/ActionButton/ActionButton.tsx
> +                    <Button onClick={() => dispatch(signOutAction())} {...rest}>
Кажется уже упоминал про хук [useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback). Его стоит использовать для всех хендлеров, чтобы они не пересоздавались на каждый рендер компонента

2020-11-27 01:12 UTC, jarith commented on app/src/components/ActionButton/ActionButton.tsx
> +);
>  Но не вижу в это какой-то выгоды

Выгода в разделении ответственности. Намного проще понять и протестировать маленький компонент с простой логикой

2020-11-27 01:12 UTC, jarith commented on app/src/components/AuthButton/AuthButton.tsx
> -                signIn(data);
Кстати, в новом компоненте куда-то потерялся диспатч экшена входа

2020-11-27 01:12 UTC, jarith commented on app/src/components/ActionButton/ActionButton.tsx
> +                    <Button onClick={hist.goBack} {...rest}>
Вообще от кнопки`Назад` ожидается возврат к предыдущей странице сайта, а не возврат по истории. Например, если при структуре `Главная -> Меню игры -> Лидерборд` на странице Лидерборда я нажму `Назад`, то ожидаю попасть в Меню игры.
Эта кнопка сработает неверно, если на Лидерборд я зайду по прямой ссылке.

Для навигации по истории есть браузерные кнопки, не вижу смысла их дублировать в интерфейсе

2020-11-27 14:28 UTC, FellonOne approved these changes

2020-12-01 15:57 UTC, Jarith approved these changes

2020-12-01 15:57 UTC, merged