feature/spinner-on-auth
PraktikumSeoulDevTeam/castleofghosts pull request #32
Opened 2020-11-27 07:31 UTC by FellonOne

Add withLoading HOC
Add Spinner component;
Update Authorization and Registration pages -> add spinner after sending request

2020-11-27 10:00 UTC, art4vm commented on app/src/hoc/withLoading.tsx
> +        const dispatcher = useDispatch();
Так используем хуки и connect?

2020-11-27 10:38 UTC, art4vm requested changes
При использовании глобального стейта со спиннером, думаю стоит использовать 1 компонент. В текущей реализации есть теоретичесчкая возможность создать одновременно несколько спиннеров, если будут загружены несколько компонентов с хоком withSpinner.

Так же немного(много), что для использования хока withSpinner необходимо модифицировать сам компонент, который без данного хока работать не сможет

Я думаю достаточно будет сделать глобальный компонент спиннер, подписать его на поле в стейте, а поле изменять либо в сагах, либо интерцепторах axios(для если нужно показывать совсем при любых запросах).

2020-11-27 10:38 UTC, art4vm commented on app/src/hoc/withLoading.tsx
> +        const dispatcher = useDispatch();
Так используем хуки и connect?

2020-11-27 10:38 UTC, art4vm commented on app/src/pages/AuthorizationPage/AuthorizationPage.tsx
> +    }, []);
Если это троббер на запросы к API, то и запускать его можно там же где идет запрос к API

2020-11-27 10:38 UTC, art4vm commented on app/src/hoc/withLoading.tsx
> +                    <Spinner />
судя по стилям, создается backdrop на всю страницу. Тогда и компонент может быть глобальным, не обязательно его добавлять перед каждым компонентом

2020-11-27 10:38 UTC, art4vm commented on app/src/hoc/withLoading.tsx
> +        return <Component setLoading={setLoading} {...props} />;
Проверять на необходимость отображения лучше в самом компоненте спиннера

2020-11-27 11:02 UTC, FellonOne commented on app/src/pages/AuthorizationPage/AuthorizationPage.tsx
> +    }, []);
В теории его можно запускать везде. Т.е. разработчик сам решать, где вызвать setLoading
Не надо привязывать это к апи
Далее, это можно использовать при генерации карты. Если же алгоритм будет очень медленный, то стоит пользователю показать Спиннер, пока генерируется уровень

2020-11-27 11:05 UTC, FellonOne commented on app/src/hoc/withLoading.tsx
> +        const dispatcher = useDispatch();
В ХОКах думаю можно хуки, т.к. в дев тулзах будет портянка из нескольких HOC
Ибо у компонента, к которому применили HOC, уже может быть пременен HOC Connect (как и в данном кейсе)
И получается такая цепочка:
Connect -> WithLoader -> Connect -> Auth/Reg Component

Но чтоб выглядело все однородно, надо вернуть на connect

2020-11-27 11:26 UTC, art4vm commented on app/src/pages/AuthorizationPage/AuthorizationPage.tsx
> +    }, []);
А как вызов API(или сагах) ограничивает его вызов в других местах?

2020-11-27 14:45 UTC, art4vm reviewed
В целом ок
Несколько мелких замечаний написал

2020-11-27 14:45 UTC, art4vm commented on app/src/layouts/UiLayout/UiLayout.tsx
> +            <Spinner />
Лайаутов может быть несколько.
Можно вообще вынести в App.tsx перед роутером

2020-11-27 14:45 UTC, art4vm commented on app/src/components/Spinner/Spinner.tsx
> +    );
```suggestion
    return isLoading && (
        <div className="spinner-block">
            <div className="loader" />
        </div>
    );
```

2020-11-27 14:45 UTC, art4vm commented on app/src/store/Utility/reducer.ts
> +    isLoading: false
Скорей всего возникнет ситуация, когда будет установлено 2 спиннера с 2 различных мест(например API и canvas или 2 параллельных запросов API), и первый же utilitySetLoading(false) его закроет. 
Можно использовать counter: number;  И показывать спиннер когда counter === 0

2020-11-27 14:45 UTC, art4vm commented on app/src/pages/RegistrationPage/RegistrationPage.tsx
> +export const RegistrationPage = compose(connecter)(RegistrationComponent);
compose по идее не нужен. Разве только для удобства в devtools
и connecter -> connector

2020-11-29 05:58 UTC, FellonOne commented on app/src/store/Utility/reducer.ts
> +    isLoading: false
Не возникнет. Мы сами устанавливаем, когда запускать спиннет, а когда вырубать
Просто не надо будет создавать таких случаев
Мне кажется это уже звучит плохо, что нужно менять isLoading на counter, чтоб одновременно запускать два спиннера? Просто не будет так делать и все

2020-11-29 09:38 UTC, art4vm approved these changes

2020-11-29 09:38 UTC, art4vm commented on app/src/layouts/UiLayout/UiLayout.tsx
> +        </>
```suggestion
        <main className="ui pa-8">
            <div className={`ui__container pa-5 ${isBlock ? 'ui__block' : ''} ${className || ''}`}>{children}</div>
        </main>
```

2020-11-29 09:38 UTC, art4vm commented on app/src/store/Utility/reducer.ts
> +    isLoading: false
> Мы сами устанавливаем, когда запускать спиннет, а когда вырубать

Это как с багами, код программист сам пишет, а баги возникают сами собой
> Мне кажется это уже звучит плохо, что нужно менять isLoading на counter, чтоб одновременно запускать два спиннера

Спинеры запускаются там где они необходимы. Время запуска вполне может пересекаться. Отслеживать где и когда вызывать спиннер, чтобы ничего не пересеклось, вот это звучит плохо

В этом приложении скорей всего не возникнет такая необходимость. Поэтому это было просто предложение

2020-12-01 13:16 UTC, kdeit approved these changes

2020-12-01 13:16 UTC, kdeit commented on app/src/store/Utility/reducer.ts
> +    isLoading: false
В одном проекте однажды долго не мог найти, где увеличил счётчик и не уменьшил. Дебажил долго, пока не сделал не counter'ом, а стеком в который попадает string с идентификатором (названием метода).

2020-12-01 13:16 UTC, kdeit commented on app/src/components/Spinner/Spinner.scss
> +}
Я бы только z-index добавил. 2000

2020-12-01 13:16 UTC, kdeit commented on app/src/components/Spinner/Spinner.scss
> +    font-size: 10px;
font-size лишний

2020-12-01 13:16 UTC, kdeit commented on app/src/components/Spinner/Spinner.scss
> +    font-size: 10px;
Да и ниже тогда не нужно

2020-12-01 14:25 UTC, art4vm commented on app/src/store/Utility/reducer.ts
> +    isLoading: false
> 
> 
> В одном проекте однажды долго не мог найти, где увеличил счётчик и не уменьшил. Дебажил долго, пока не сделал не counter'ом, а стеком в который попадает string с идентификатором (названием метода).

Ну как вариант

2020-12-01 15:09 UTC, art4vm commented on app/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +);
```suggestion
);

```

2020-12-01 15:55 UTC, merged