Feature/feature update user saga
PraktikumSeoulDevTeam/castleofghosts pull request #39
Opened 2020-12-01 12:33 UTC by kdeit

#59 Обновление пользователя. Работа со Store (Redux Saga)

2020-12-01 14:18 UTC, art4vm requested changes

2020-12-01 14:18 UTC, art4vm commented on app/src/api/index.ts
> +export async function updateUserAvatar(data: ApiChangeAvatarRequest): Promise<ApiUserInfo> {
на сервер уходит FormData а не JSON

2020-12-01 14:18 UTC, art4vm commented on app/src/api/types.ts
> +
такой тип не подходит для FormData

2020-12-01 14:18 UTC, art4vm commented on app/src/components/FormControl/types.ts
> +export type FormControlFieldType = 'text' | 'password' | 'email' | 'file' | 'hidden';
id не нужно на странице. Его можно подмешивать при запросе в saga

2020-12-01 14:18 UTC, art4vm commented on app/src/components/UserAvatarChange/UserAvatarChange.tsx
> +            {user.avatar && <img src={user.avatar} alt={user.first_name} className="mt-2 mb-2" />}
```suggestion
            {user.avatar && <img src={user.avatar} alt={user.first_name} className="my-2" />}
```

2020-12-01 14:18 UTC, art4vm commented on app/src/store/User/sagas.ts
> +    } catch (error) {
тут возвращается ApiUserInfo, его нужно передать в store

2020-12-01 14:18 UTC, art4vm commented on app/src/store/User/types.ts
>      UPDATE = 'cog/user/update',
тут началась путаница с actions. В частности, идет обновление user при старте приложения. Это Update чего, на сервере или в хранилище? Добавь action SAVE для сохранения в хранилище

2020-12-01 14:18 UTC, art4vm commented on app/src/components/UserAvatarChange/UserAvatarChange.tsx
> +    };
При обновлении аватара, компонент не обновляется
Если избавиться от `alt={user.first_name}` то можно установить завасимость только от поля `avatar`

2020-12-01 18:40 UTC, kdeit commented on app/src/store/User/types.ts
>      UPDATE = 'cog/user/update',
Нет никакой путаницы. Есть GET ( при старте) есть UPDATE. Второй меняет и на сервере и соотвественно должен поменять в хранилище. Зачем вводить ещё одно?

2020-12-01 18:42 UTC, kdeit commented on app/src/components/UserAvatarChange/UserAvatarChange.tsx
> +    };
ALT нельзя убирать для img. Это как-то неверно по сути.

2020-12-01 18:47 UTC, kdeit commented on app/src/api/types.ts
> +
А что не так? Поле типа File.... Что ты предлагаешь?

2020-12-01 19:50 UTC, art4vm commented on app/src/store/User/types.ts
>      UPDATE = 'cog/user/update',
UPDATE на сервере и UPDATE в хранилище локально, это разные задачи и по смыслу и по вызовам. Тот что обновляет данные в локальном хранилище, вызывается почти при всех вызовах API связанных с user

2020-12-01 19:55 UTC, art4vm commented on app/src/components/UserAvatarChange/UserAvatarChange.tsx
> +    };
alt можно и оставить, а имя убрать. Можно и имя в принципе оставить(imho не лучший вариант для image в данном случае), но тогда нужно либо свой компаратор в connect передавать, либо не на весь info подписываться, а отдельно на 2 поля

2020-12-01 19:58 UTC, art4vm commented on app/src/api/types.ts
> +
В объекте FormData нет полей там иттератор. Собственно новый тип вообще не нужен, достаточно передавать FormData как и было в API

2020-12-04 10:21 UTC, kdeit commented on app/src/store/User/types.ts
>      UPDATE = 'cog/user/update',
Понял ошибку. Поправил.

2020-12-04 10:22 UTC, kdeit commented on app/src/api/types.ts
> +
Менее явно, но ОК

2020-12-04 10:38 UTC, Jarith commented on app/src/components/UserAvatarChange/UserAvatarChange.tsx
> +    };
Лучше отдельно подписаться на `avatar` и `first_name`

2020-12-04 10:39 UTC, Jarith approved these changes
В `UserAvatarChange.tsx` стоит отдельно получать поля `first_name` и `avatar` и порешать конфликты в PR

2020-12-04 12:10 UTC, art4vm approved these changes

2020-12-04 12:18 UTC, merged

2020-12-08 18:13 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Обновление пользователя. Работа со Store (Redux Saga)](https://trello.com/c/nNnsCfBW/59-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81%D0%BE-store-redux-saga)