Feature/feature welcome screens
PraktikumSeoulDevTeam/castleofghosts pull request #4
Opened 2020-11-04 15:56 UTC by kdeit

2020-11-04 16:42 UTC, art4vm reviewed
Основной вопрос, это структура каталогов. Я бы предложил assets вынести из src, чтобы там был только код. А стили в свою очередь вынести из assets, в итоге будет 3 каталога в app
- assets
- styles (ну или scss/css не важно)
- src

2020-11-04 16:42 UTC, art4vm commented on app/src/assets/scss/_reset.scss
> +}
Может что-нибудь вроде [reset-css](https://www.npmjs.com/package/reset-css) заиспользовать?

2020-11-04 16:42 UTC, art4vm commented on app/src/assets/scss/_typo.scss
> +    src: url('data:application/font-woff2;charset=utf-8;base64,d09GMgABAAAAAAnUAA0AAAAAI6wAAAl7AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP0ZGVE0cGh4GYACCYhEICq1gniALgVIAATYCJAOBWAQgBY09B4IAGzIaE26MPGwcEBDu7WT/
Может в отдельный woff2 файл лучше вынести?

2020-11-04 16:42 UTC, art4vm commented on app/src/components/button/types.ts
> +export type Props = OwnProps;
Я бы предложил избавиться от импортов и экспортов в типах. Это избавит от кучи импортов в файлах

2020-11-04 16:42 UTC, art4vm commented on app/www/index.html
> +    </body>
Тут надо бы договориться как такое будем форматировать @FellonOne @kdeit. Очень часто head и body не сдвигают и это стандартное поведение многих IDE по умолчанию.

2020-11-04 16:42 UTC, art4vm commented on package.json
> +    "sass-loader": "^10.0.5"
это devdependencies и надо бы залочить версию

2020-11-04 16:42 UTC, art4vm commented on package.json
> +    "webpack": "^5.4.0",
тут версию тоже залочить

2020-11-04 16:50 UTC, kdeit commented on app/src/assets/scss/_typo.scss
> +    src: url('data:application/font-woff2;charset=utf-8;base64,d09GMgABAAAAAAnUAA0AAAAAI6wAAAl7AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP0ZGVE0cGh4GYACCYhEICq1gniALgVIAATYCJAOBWAQgBY09B4IAGzIaE26MPGwcEBDu7WT/
А чем отдельный лучше?
Тут минус http запрос.

2020-11-04 16:51 UTC, kdeit commented on app/src/assets/scss/_reset.scss
> +}
А что там есть чего тут нет?
Да и тут мы своё можем добавить. Например, отключение IOS-украшалок на элементах формы.
Чего не сделал, кстати.

2020-11-05 05:34 UTC, FellonOne requested changes
Привет) Оставил парочку комментарий! Можно их обсудить будет в слаке! Там мне быстрее приходят уведомления, чем на гитхаб(

2020-11-05 05:34 UTC, FellonOne commented on app/src/components/welcome-page/welcome-page.tsx
> +import React from 'react';
Привет! В Реакте принято называть файлы, содержащие компонент, с большой буквы
И использовать при наименовании CamelCase формат. Если смотреть доку реакта, то во всех примерах они используют такую вот систему именование файлов. Всякие утилиты и прочие, называют с маленькой буквой (но так же в нотации CamelCase)
https://ru.reactjs.org/docs/faq-structure.html
https://medium.com/@timafon/%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%B8-%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%B2-react-2a29e96e0e07

Почему это плюс:
- По названию файла легко определить Компонент это или нет
- По названию папки можно понять, что она содержит компоненты

2020-11-05 05:34 UTC, FellonOne commented on app/src/components/button/Button.tsx
> +}
Если у компонента отсутствует состояние, то рекомендуется использовать функциональные компоненты
С выходом React Hooks (https://reactjs.org/docs/hooks-intro.html), смысл использовать компонента классы отпадает, так как в функциональных появилась возможность использовать стейты и жизенные циклы компонента.
Плюсы функ. компо - меньше боилерПлейт кода
```
class Button extends PureComponent<Props> {
    public render(): JSX.Element {
        const {className, children} = this.props;

        return (
            <button className={className} type="button">
                {children}
            </button>
        );
    }
}
```


```
function Button ({ className, children}): JSX.Element {
      return (
            <button className={className} type="button">
                {children}
            </button>
      );
}
```

2020-11-05 07:49 UTC, FellonOne commented on app/www/index.html
> +    </body>
У нас же преттир так же умеет форматировать html. Будем форматировать через него

2020-11-05 08:13 UTC, art4vm commented on app/src/assets/scss/_reset.scss
> +}
> А что там есть чего тут нет?
Ну так про многое можно сказать)
Обычно, если проект популярный, не вижу причин им не пользоваться.

>  отключение IOS-украшалок на элементах формы
Не думаю что стоит прям все отключать, обычно проблемы часто с размерами возникают

Так же предлагаю в дальнейшем использовать autoprefixer из postcss

2020-11-05 08:17 UTC, art4vm commented on app/src/assets/scss/_typo.scss
> +    src: url('data:application/font-woff2;charset=utf-8;base64,d09GMgABAAAAAAnUAA0AAAAAI6wAAAl7AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP0ZGVE0cGh4GYACCYhEICq1gniALgVIAATYCJAOBWAQgBY09B4IAGzIaE26MPGwcEBDu7WT/
Будет или не будет отдельного http запроса это вопрос вэбпака.
А лучше, ну как минимум, если вдруг возникнет необходимость поменять шрифт, достаточно будет поменять файл(ну и путь к нему) без необходимости кодировать в base64 еще и с большим diff в гите

2020-11-05 08:18 UTC, art4vm commented on app/src/components/button/types.ts
> +export type Props = OwnProps;
Типы не нужно импортировать, они доступны для всего проекта. МОжно даже сторонние подключить, в tsconfig есть отдельныей параметр для этого

2020-11-05 08:19 UTC, art4vm commented on app/www/index.html
> +    </body>
В целом это избыточно, но ок

2020-11-05 08:29 UTC, art4vm commented on app/src/components/button/Button.tsx
> +}
Предлагаю использовать всегда классы, они лучше ложаться по смыслу на компоненты

2020-11-05 09:35 UTC, FellonOne commented on app/src/components/button/Button.tsx
> +}
> Предлагаю использовать всегда классы, они лучше ложаться по смыслу на компоненты

К сожалению, в мире реакта, классы ушли на второй план, с приходом хуков, не имеет никакого смысла использовать классы-компоненты. Нужно учиться работать с функциональными компонентами и хуками. Про классы надо знать, знать лайфайкл методы, синтаксис и тд. Но их время подходит к концу

Тут можно почитать, как развивались функц. компоненты
https://medium.com/better-programming/pros-cons-of-functional-components-in-react-f52bded98db0
И какие сущ. отличия между классом и функц. комп.
https://overreacted.io/how-are-function-components-different-from-classes/

2020-11-05 09:41 UTC, FellonOne commented on app/src/components/button/types.ts
> +export type Props = OwnProps;
А, ты имеешь ввиду, настроить tsconfig и IDE так, что она сама автоматом будет подцеплять типы и показывать их?
Про такое не знал если честно, вроде звучит круто

2020-11-05 09:44 UTC, FellonOne commented on app/src/assets/scss/_reset.scss
> +}
Если не ошибаюсь, у нас не настроен postcss( 
нужно будет его настроить

2020-11-05 11:56 UTC, art4vm commented on app/src/assets/scss/_reset.scss
> +}
> (

не настроен, но там пару строчек в webpack

2020-11-06 10:24 UTC, art4vm commented on app/www/index.html
> +    </body>
Разница возникла из за того, что я локально форматирую html не через prettier

2020-11-10 00:10 UTC, jarith commented on .eslintrc.json
> +    "no-console": "off",
Пропустил в одном из прошлых PR. Надо бы включить опцию. Полезна, чтобы не пропускать в коде случайные `console.log`

2020-11-10 00:10 UTC, jarith commented on app/src/assets/scss/_variables.scss
> +$color1: #d34549;
Я бы предложил давать более осмысленные имена цветам. Например `primary`, `secondary`, ... как в Material Design. Это полезно, если подразумевается смета цветовой палитры.
Просто названия цветов, вроде `pinkRed`, тоже будут норм

2020-11-10 00:10 UTC, jarith commented on app/src/components/App.tsx
>  }
```suggestion
const App = () => <WelcomePage />;

export default App;
```

2020-11-10 00:10 UTC, jarith commented on app/webpack.config.js
> +                test: /\.s[ac]ss$/i,
Предлагаю использовать только `scss` синтаксис. Соответственно и собирать только такие файлы

2020-11-10 00:10 UTC, Jarith commented on app/src/components/welcome-page/welcome-page.tsx
> +        <div className="ui">
Использование jsx - не повод отказываться от семантической верстки 🙂
```suggestion
        <main className="ui">
```

2020-11-10 00:10 UTC, Jarith commented on app/src/components/welcome-page/welcome-page.tsx
> +                    <div className="welcome--page__title t-title">
```suggestion
                    <h1 className="welcome--page__title t-title">
```

2020-11-10 00:10 UTC, Jarith commented on app/src/components/welcome-page/welcome-page.tsx
> +                        <br />
Лучше не использовать `<br />`, а обернуть каждое слово в `<span>` и задать им расположение при помощи CSS

2020-11-10 00:10 UTC, Jarith commented on app/src/components/welcome-page/welcome-page.tsx
> +export default function WelcomePage(): JSX.Element {
Давайте помимо `components` заведем еще папку `pages`, куда как раз попадут корневые элементы как `WelcomePage`.

Суффикс `Page`, кстати, можно будет тогда убрать

2020-11-10 00:10 UTC, Jarith commented on app/src/components/welcome-page/welcome-page.tsx
> +                <div className="ui__bottom">
```suggestion
                <footer className="ui__bottom">
```

В целом полностью футер можно вынести в отдельный компонент

2020-11-10 14:11 UTC, kdeit commented on app/src/components/welcome-page/welcome-page.tsx
> +                <div className="ui__bottom">
А он у нас больше нигде в таком виде не встречается. Может больно жирно ему свой компонент? :)

2020-11-10 14:38 UTC, art4vm commented on app/src/components/welcome-page/welcome-page.tsx
> +                <div className="ui__bottom">
Футер можно на каждой странице прилепить. А тут возможно все же не совсем футер, я не нашел класса ui__bottom

2020-11-10 15:08 UTC, art4vm requested changes

2020-11-10 15:08 UTC, art4vm commented on .eslintrc.json
> +    "no-console": 2,
предлагаю всегда писать словами (error вместо 2) и тут установить в "warn", тк в процессе работы часто приходится писать вывод логов, не хочу чтобы код был красным от этого. Warn pre--commit так же не пропускает.

2020-11-10 15:08 UTC, art4vm commented on app/src/components/button/types.ts
> +export type OwnProps = {
Предлагаю такое называть интерфейсом, тк по сути это декларация формата объекта. Тогда можно будет просто пронаследоваться от ButtonHTMLAttributes

2020-11-10 15:08 UTC, art4vm commented on app/src/components/button/types.ts
> +export type Props = OwnProps;
Думаю не стоит дублировать типы

2020-11-10 15:08 UTC, art4vm commented on app/src/components/button/index.ts
> +export default memo<OwnProps>(Button);
Предлагаю избавиться от index файлов, не выжу в них смысла

2020-11-10 15:08 UTC, art4vm commented on package.json
> +    "mini-css-extract-plugin": "1.2.1",
это devdependency

2020-11-10 15:08 UTC, art4vm commented on app/src/components/button/Button.tsx
> +export default Button;
можно сразу экспортировать. Так же вроде обсуждали дэфолтные экспорты, решили не использовать(или нет?)

2020-11-12 08:05 UTC, kdeit commented on app/src/components/button/types.ts
> +export type Props = OwnProps;
Own props потом используется в мемоизации в index.ts

2020-11-12 08:05 UTC, kdeit commented on app/src/components/button/index.ts
> +export default memo<OwnProps>(Button);
На собрании договорились их использовать.

2020-11-12 08:05 UTC, kdeit commented on app/src/components/button/types.ts
> +export type OwnProps = {
Договорились рефакторить в дальнейшем

2020-11-12 09:57 UTC, kdeit commented on app/src/components/button/Button.tsx
> +export default Button;
Переделал.
1 - Убрал export default
2 - Добавил index.ts в components и pages
3 - Там, где не нужно, убрал из папки компонента index.ts
4 - Но оставил, например, там где идёт обёртка memo в компоненте

2020-11-12 12:00 UTC, art4vm commented on app/src/assets/scss/_variables.scss
> +$colorBackDark: #140c1c;
Я бы предложил именовать так же, как и в css через '-'

2020-11-12 12:00 UTC, art4vm commented on app/src/components/button/types.ts
> +export type Props = OwnProps;
Это я понял, но зачем? Было бы логичней использовать именно Props и совсем избавиться от OwnProps

2020-11-12 12:00 UTC, art4vm commented on app/src/pages/Welcome/Welcome.scss
> +        &__item {
Тут не соответсвует BEM тк `item` это элемент блока `welcome-page` т.е. должно быть `welcome-page__item` либо `welcome-page__title-item` либо если это модификатор то `welcome-page__title_item`, но тогда нужно придумать другое название. В текущей реализации получается `welcome-page__title__item`

2020-11-12 12:00 UTC, art4vm commented on app/src/components/index.ts
> +export * from './Copyright/Copyright';
При обсуждении импорта типов, решили что явное лучше неявного, а данная реализация(а так же index.ts у компонентов) по сути невелирует данное утверждение.
Так же возникают двойные(и даже тройные) экспорты компонентов, те можно импортировать как напряму, так и из index.ts(или какого нибудь другого index.ts который будет встречаться в иерархии). А как видно из реализации, например компонента button, в обоих файлах одинаковое название, но разная функциональность(добавляется memo). Например в данном файле 1 импорт из index второй напрямую из компонента
Еще одной проблемой может быть сложность при дроблении сборки на чанки(где-то есть требование в задании).

2020-11-12 12:00 UTC, art4vm commented on app/src/assets/scss/sizing.scss
> +}
- Часто необходимы размеры только по вертикали или только по горизонтали. Можно конечно использовать варианты как сейчас `p--r__4 p--l__4`, но думаю довольно просто будет добавить варианты вроде `p--x__4`
- Наименования можно сократить, по аналогии с bootstrap, например `p--a__5` -> `pa-5`

2020-11-12 14:15 UTC, Jarith commented on app/src/components/button/types.ts
> +export type Props = OwnProps;
Поддержу. Я бы не дублировал и назвал тип `ButtonProps`

2020-11-12 14:18 UTC, Jarith commented on app/src/components/button/Button.tsx
> +function Button(props: Props): JSX.Element {
Предлагаю

```suggestion
function Button({children, className = 'btn t-main'}: Props): JSX.Element {
```

И убрать `Button.defaultProps` ниже

2020-11-13 10:53 UTC, FellonOne commented on .eslintrc.json
> +    "no-console": 2,
Согласен. Словами сразу понятно, в каком состоянии находится параметр. Явное лучше неявного

2020-11-13 14:52 UTC, Jarith approved these changes

2020-11-13 14:59 UTC, FellonOne approved these changes

2020-11-13 14:59 UTC, art4vm approved these changes

2020-11-13 15:07 UTC, merged