feature/toast
PraktikumSeoulDevTeam/castleofghosts pull request #40
Opened 2020-12-01 15:27 UTC by FellonOne

Add Toast in project

2020-12-03 17:36 UTC, art4vm requested changes

2020-12-03 17:36 UTC, art4vm commented on app/src/store/Toaster/actions.ts
> +}): ToasterCreateAction {
Есть же интерфейс

2020-12-03 17:36 UTC, art4vm commented on app/src/store/Toaster/sagas.ts
> +    const toasterId = `${Date.now()}_${Math.trunc(Math.random() * Date.now())}`;
зачем тут это` Math.trunc(Math.random() * Date.now()`? Просто `Date.now()` не хватает?

2020-12-03 17:36 UTC, art4vm commented on app/src/store/Toaster/reducer.ts
> +            });
```suggestion
            newState.toastes.push(action.payload);
```

2020-12-03 17:36 UTC, art4vm commented on app/src/store/Toaster/types.ts
> +    REMOVE_TOASTER = 'cost/toaster/remove'
```suggestion
    ADD_TOASTER = 'cog/toaster/add',
    CREATE_TOASTER = 'cog/toaster/create',
    REMOVE_TOASTER = 'cog/toaster/remove'
```

2020-12-03 17:36 UTC, art4vm commented on app/src/store/User/sagas.ts
> +        );
Почему вызов только в этом месте?
Текст с ошибкой уже существует в error

2020-12-03 17:36 UTC, art4vm commented on app/src/components/Toaster/Toaster.tsx
> +});
```suggestion
const mapActionToProps = {
    removeToast: toasterRemoveAction
};
```

2020-12-03 17:36 UTC, art4vm commented on app/src/components/Toaster/Toaster.tsx
> +
сейчас нет правила разделения импортов по группам пустой строкой

2020-12-03 17:36 UTC, art4vm commented on app/src/components/Toaster/Toaster.tsx
> +        </Button>
не вижу смысла использовать компонент Button, тк он только устанавливает стили, которые тут все равно не нужны

2020-12-03 17:36 UTC, art4vm commented on app/src/components/Toaster/Toaster.tsx
> +            {toasts.map((toast) => (
```suggestion
            {toasts.map(({id, text}) => (
```

2020-12-03 17:36 UTC, art4vm commented on app/src/components/index.ts
> +export * from './Menu/Menu';
В конце всех файлов должна быть пустая строка. В ESLint есть правило

2020-12-03 17:36 UTC, art4vm commented on app/src/store/Toaster/sagas.ts
> +}
а зачем вообще параметр duration в store если тут просто ставится delay?
Предлагаю избавиться от него и всегда устанавливать 3сек. Сомневаюсь что тосты когда-нибудь будут иметь разное время жизни

2020-12-03 17:36 UTC, art4vm commented on app/src/store/Toaster/sagas.ts
> +    );
Судя по действиям, CREATE от ADD action отличается только добавлением id. Предлагаю избавиться от CREATE action, а id ставить в ADD action

2020-12-03 17:36 UTC, art4vm commented on app/src/store/Toaster/actions.ts
> +export function toasterAddAction({text, duration}: {text: string; duration?: number}): ToasterAddAction {
Предлагаю избавиться от duration вообще и добавить id = Date.now()
см комментарий в saga

2020-12-03 17:36 UTC, art4vm commented on app/src/store/rootReducer.ts
>      utility: utilityReducer
```suggestion
    utility: utilityReducer,
    toaster: toasterReducer
```

2020-12-04 12:05 UTC, FellonOne commented on app/src/store/Toaster/sagas.ts
> +    const toasterId = `${Date.now()}_${Math.trunc(Math.random() * Date.now())}`;
В теории да, просто доп рандомное число

2020-12-04 12:05 UTC, FellonOne commented on app/src/store/User/sagas.ts
> +        );
Да, это была старая версия

2020-12-04 12:07 UTC, FellonOne commented on app/src/store/Toaster/sagas.ts
> +}
Кастомизация и не более. Предлагаю оставить
Ибо вдруг где-нибудь понадобится вызвать тост на любое кастомное время

2020-12-05 11:08 UTC, FellonOne commented on app/src/store/Toaster/sagas.ts
> +    );
Ну CREATE создает запись в сторе
ADD - action для саги - медиатор, который создает тост и потом его удаляет
Это как у Users, Тип есть signIn сага и saveUser (без саги), так вот signIn пораждает другие action
Тут так же ADD пораждает CREATE и DELETE (после задержки)

`
function* toasterAdd(action: ToasterAddAction) {
    const toasterId = `${Date.now()}`;

    yield put(
        toasterCreateAction({
            id: toasterId,
            text: action.payload.text,
            duration: action.payload.duration ?? DEFAULT_TOAST_ACTIVE_TIME
        })
    );

    yield delay(action.payload.duration ?? DEFAULT_TOAST_ACTIVE_TIME);
    yield put(toasterRemoveAction(toasterId));
}
`
Тип, если же убрать toasterCreateAction, то выполнение reducer на toasterAdd action будет запущено после выполнения всей саги toasterAdd и непонятно как потом вызвать yield put(toasterRemoveAction(toasterId)); чтоб удалить тост

2020-12-07 11:27 UTC, art4vm commented on app/src/store/Toaster/sagas.ts
> +    );
signIn и saveUser это разные действия, которые совсем никак не связаны. Даже обновление пользователя в store и на сервере, это разные действия. Напрямую в сторе user не должен сохраняться, только как результат сохранения на сервере.
Тут из сайд эффектов только запуск таймера на удаление, зачем делать прокси на добавление в хранилище? Если удалить toasterCreateAction ничего не изменится

2020-12-07 11:27 UTC, art4vm commented on app/src/api/interceptors.ts
> +}
1. Не понял, зачем ты вынес интерцепторы из файла с API? Это неотъемлемая часть API и без него использоваться не может, это коллбэки
2. Вызов тут мне нравится, но вызов в сагах был более универсальным, нужно только добавить вызов в другие саги.  Сейчас если пользователь неавторизован, он сразу получит ошибку, тк при старте идет запрос информации пользователя

2020-12-07 11:27 UTC, art4vm commented on app/src/store/Toaster/sagas.ts
> +    const toasterId = `${Date.now()}`;
Раз бто цифровой id можно без строки, просто Date.now()

2020-12-08 08:26 UTC, FellonOne commented on app/src/api/interceptors.ts
> +}
1. Для удобства работы с файлами. Файл api.ts превращается в гигантскую простыню кода. Я сделал разделение на части. интерцепторы лежат в папке с API, т.е. сразу понятно, что они относятся к нему и нет никакого разделения. 
2. Вроде решили вызывать в интерцепторах? Тогда уберу, и верну вызов тостов в Сагах. Действительно, если неавторизован, то вылезает тост

2020-12-08 12:58 UTC, FellonOne commented on app/src/store/Toaster/sagas.ts
> +    );
Поменяется. Нельзя в toasterAddAction добавить функционал createAction
Потому что мы используется метод yield sleep()
`function* toasterAdd(action: ToasterAddAction) {
    const toasterId = `${Date.now()}`;
    yield put(
        toasterCreateAction({
            id: toasterId,
            text: action.payload.text,
            duration: action.payload.duration ?? DEFAULT_TOAST_ACTIVE_TIME
        })
    );

    yield delay(action.payload.duration ?? DEFAULT_TOAST_ACTIVE_TIME);
    yield put(toasterRemoveAction(toasterId));
}
`
Т.е. это сага которая выполняет 2 действия -> вызывает action на запись в сторе и action на удаление из стора

2020-12-08 18:09 UTC, art4vm commented on app/src/App.tsx
> +import './api/interceptors';
Я предлагаю все же вернуть интерцепторы в index.ts
Такой вариант размазывает логику инициализации API

2020-12-11 11:02 UTC, art4vm approved these changes

2020-12-13 06:17 UTC, Jarith approved these changes

2020-12-13 06:17 UTC, merged

2020-12-15 07:06 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать механизм всплывающих сообщений](https://trello.com/c/FVWiqN1h/56-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BC%D0%B5%D1%85%D0%B0%D0%BD%D0%B8%D0%B7%D0%BC-%D0%B2%D1%81%D0%BF%D0%BB%D1%8B%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D1%85-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9)