Feature/feature game start page
PraktikumSeoulDevTeam/castleofghosts pull request #42
Opened 2020-12-06 15:32 UTC by kdeit

Add start page
Leaderboard to new page
Add countdown for start
Add Game/Action

2020-12-07 11:35 UTC, art4vm requested changes

2020-12-07 11:35 UTC, art4vm commented on app/src/components/Menu/Menu.tsx
> -                        </Link>
Это не нужно убирать из меню

2020-12-07 11:35 UTC, art4vm commented on app/src/utils/history.ts
> +export default createBrowserHistory();
зачем создавать отдельный объект с историей, если он и так уже есть внутри роутера?

2020-12-07 11:35 UTC, art4vm commented on app/src/store/Game/sagas.ts
> +}
Установка char_name не имеет никаких сайд эффектов, saga вообще не нужна

2020-12-07 11:35 UTC, art4vm commented on app/src/router/AppRouter/AppRouter.tsx
> +        <Router history={history}>
<s>скрипач</s>history не нужен

2020-12-07 11:35 UTC, art4vm commented on app/src/pages/StartPage/StartPage.tsx
> +            <Leaderboard />
верни страницу leaderboard

2020-12-07 11:35 UTC, art4vm commented on app/src/pages/StartPage/StartPage.tsx
> +            history.push('/game');
1. если объект history нужен только для этого, то есть useHistory
2. действия перехода должно возникнуть по факту какого-то события, а не само по себе, например сменилость состояние из за gameStartAction

2020-12-07 11:35 UTC, art4vm commented on app/src/components/CharNameInput/CharNameInput.tsx
> +}
В приложении уже есть готовый вариант создания формы. Тут просто форма с 1 полем

2020-12-07 11:35 UTC, art4vm commented on .eslintrc.json
> +      },
1. Путь не верный, корневой путь ресолва .src видимо используется путь из tsconfig
2. Нужна правка в самом tsconfig(добавить path)
3. Нужно поправить во всем проекте где есть импорт с '..'
предлагаю это вынести в отдельный пул реквест.

2020-12-07 11:35 UTC, art4vm commented on app/src/components/CharNameInput/CharNameInput.tsx
> +};
Это выглядит как mapDispatch а не merge
Так же выполнять диспатч на onchange кажется избыточным

2020-12-07 12:16 UTC, kdeit commented on app/src/components/Menu/Menu.tsx
> -                        </Link>
См. карточку

2020-12-07 12:16 UTC, kdeit commented on app/src/pages/StartPage/StartPage.tsx
> +            <Leaderboard />
См. карточку

2020-12-07 12:19 UTC, kdeit commented on app/src/components/CharNameInput/CharNameInput.tsx
> +}
Текущая реализация формы подразумевает события Submit. Тут-же используется update. Чем такая реализация хуже? Если где-то ещё будет встречаться поле ввода6 не требующее Сабмит, то можно данный функционал добавить в нашу форму

2020-12-07 12:20 UTC, kdeit commented on app/src/components/CharNameInput/CharNameInput.tsx
> +};
Это именно mergeProps. Значения из state применяются в initValue

2020-12-08 17:57 UTC, art4vm commented on app/src/components/CharNameInput/CharNameInput.tsx
> +}
Formik перехватывает сабмит и выполняет любые действия.
Не то чтобы конкретно реализация чем-то плоха, просто при наличии готового вариант решения не вижу смысла повышать энтропию =)

2020-12-08 18:03 UTC, art4vm commented on app/src/pages/StartPage/StartPage.tsx
> +            <Leaderboard />
Кажется в ней неверное толкование нашего обсуждения главной страницы игры.
Тогда я говорил, что лидерборд на входе до авторизации будет не доступен, поэтому кнопку нужно перенести и предложил страницу начала игры.
1. Это было еще до внедрения меню
2. Там шла речь только про кнопку перехода на страницу лидерборда, а не сам лидерборд

2020-12-10 06:49 UTC, kdeit commented on app/src/components/CharNameInput/CharNameInput.tsx
> +}
Главная причина такой реализации — Избавление от кнопки Сабмита.

2020-12-10 07:23 UTC, kdeit commented on app/src/pages/StartPage/StartPage.tsx
> +            history.push('/game');
1 - useHistory работает только в компонентах
2 - Перенёс смену роута в сагу

2020-12-10 12:00 UTC, art4vm commented on app/src/components/CharNameInput/CharNameInput.tsx
> +}
Кнопка отправки так и так есть
Проверка на возможность отправки реализуется через проверку полей на валидность, как это сделано в других формах
Вызов countdown следует выполнять по факту перехода, а не нажатию на кнопку, тогда не будет необходимости ее отключать

2020-12-10 16:28 UTC, kdeit commented on app/src/components/CharNameInput/CharNameInput.tsx
> +}
Кнопки отправки нет. Есть отдельный компонент, который занимается своим делом — Устанавливает имя персонажа для конкретной игры. 
Страница должна быть набором компонентов. Если делать всё одной формой, то придётся логику «изменения имени» тащить на страницу или в этот компонент отправлять кнопку запуска, что тоже не верно.
Не понял по поводу «Вызов countdown следует выполнять по факту перехода»

2020-12-10 17:01 UTC, kdeit commented on .eslintrc.json
> +      },
1 - А почему не правильный? У нас-же папка server ещё есть.
2 - tsconfig поправил, в webpack.config добавил path
3 - Тут убрал, где нашёл. Получилось много изменённых файлов, но мож и к лучшему. Сразу поправим и забудем.

2020-12-10 18:07 UTC, art4vm commented on app/src/components/CharNameInput/CharNameInput.tsx
> +}
> Есть отдельный компонент, который занимается своим делом — Устанавливает имя персонажа для конкретной игры

установкой занимается хранилище при отправке некоторого action. Тут вопрос времени вызова этого action. Как и в любых формах обычно это происходит при ее отправке(даже если нужно валидировать online делают debounce, но в данном случае это не нужно). Сейчас у тебя при каждом изменении поля идет сохранение

> Страница должна быть набором компонентов

Страница ничем не отличается от любого другого компонента, это условность

> Если делать всё одной формой, то придётся логику «изменения имени» тащить на страницу или в этот компонент отправлять кнопку запуска, что тоже не верно.

Все формы в приложении сделаны одинаково. В submit выполняются action. Устанавливаешь данные из формы, и/или другие параметры состояния. При их изменении если компонент подписан на св-ва он изменится. Например можно рендерить countdown, а лучше выполнить перенаправление на другую страницу, например с игрой

> не понял по поводу «Вызов countdown следует выполнять по факту перехода

событие которое его вызывает дожно быть (в данном случае) сохранение имени персонажа или изменение стутуса игры(т.е. смена состояния приложения), а не нажание на кнопку.

2020-12-10 18:10 UTC, art4vm commented on .eslintrc.json
> +      },
> 1 - А почему не правильный? У нас-же папка server ещё есть.

Это по прежнему относительный путь и корнем является src а не app/src. Как eslint его вычисляет не знаю, возможно используется tsconfig

2020-12-11 10:02 UTC, kdeit commented on app/src/components/CharNameInput/CharNameInput.tsx
> +}
@art4vm Новый вариант залил. Посмотри, пожалуйста.

2020-12-12 06:26 UTC, art4vm commented on app/src/pages/StartPage/StartPage.tsx
> +export const StartPage = connector(component);
Чтобы тут не писать сделал [ПР](https://github.com/PraktikumSeoulDevTeam/castleofghosts/pull/48) на данный файл со всеми предлагаемыми изменениями

2020-12-14 14:31 UTC, art4vm approved these changes

2020-12-15 07:07 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница с инициализацией игры](https://trello.com/c/1zzJ7H05/49-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%81-%D0%B8%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B5%D0%B9-%D0%B8%D0%B3%D1%80%D1%8B)

2020-12-15 16:08 UTC, FellonOne approved these changes

2020-12-16 00:09 UTC, merged