Update EditPage.tsx
PraktikumSeoulDevTeam/castleofghosts pull request #44
Opened 2020-12-09 19:35 UTC by art4vm

Поменял названия на английские для единообразия и сокращения длины заголовка
Сделал заголовок динамическим

2020-12-10 06:45 UTC, kdeit requested changes

2020-12-10 06:45 UTC, kdeit commented on app/src/pages/EditPage/EditPage.tsx
> +            <h1 className="t-title">{view}</h1>
Это лишнее. Если уж делать переводы, то как-то единой техникой (i18n, например), а не такими полумерами.
В дальнейшем при внедрении переводов будет сложно искать, что переведено, что нет.

2020-12-10 11:48 UTC, art4vm commented on app/src/pages/EditPage/EditPage.tsx
> +            <h1 className="t-title">{view}</h1>
Это не перевод, весь проект на английском

2020-12-10 16:25 UTC, kdeit commented on app/src/pages/EditPage/EditPage.tsx
> +            <h1 className="t-title">{view}</h1>
Даже, если это не перевод (и переводов не будет), то сформулирую по-другому: все тексты лучше что-бы были в одном месте.
Потом открываешь 1 файлик и в нём правишь все тексты.
Например, завтра дизайнер решил, что кнопка «Ок» стала «Поехали» или «Last name» стал вдруг «Second name» во всём проекте.
А у нас получается, что где-то тексты зашиты, где-то через enum и т.д.
Я бы сейчас оставил, где можно зашитыми, что-бы потом было легче искать, если будем приводить в порядок.
Про переводы, кстати, был разговор. Даже конкрентно говорили про i18n.

2020-12-10 17:41 UTC, art4vm commented on app/src/pages/EditPage/EditPage.tsx
> +            <h1 className="t-title">{view}</h1>
>  все тексты лучше что-бы были в одном месте

как это относится к текущему ПР? Сейчас все тексты устанавливаются по месту использования, когда(если) будут переводы, тогда и решим данный вопрос


> А у нас получается, что где-то тексты зашиты, где-то через enum и т.д.

У нас везде зашиты. В данной реализации подставляется заголовок согласно текущему табу из enum, который расположен на той же странице.

2020-12-11 10:03 UTC, kdeit commented on app/src/pages/EditPage/EditPage.tsx
> +            <h1 className="t-title">{view}</h1>
В общем по кругу пошли. Ок.

2020-12-11 10:03 UTC, kdeit approved these changes

2020-12-13 06:31 UTC, Jarith approved these changes

2020-12-13 06:31 UTC, merged