add validator
PraktikumSeoulDevTeam/castleofghosts pull request #5
Opened 2020-11-05 11:57 UTC by FellonOne

add validator and base rules:
 - required
 - max-length
 - min-length
 - email - field must be an email

2020-11-05 13:09 UTC, art4vm requested changes

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/validator/functions/isEmail.ts
> +export default function isEmailt(val: string): boolean {
лишняя t

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/isEmpty.ts
> +    if (arg === null || arg === undefined || !arg) return true;
!arg приведет к тому, что например 0 тоже будет считаться пустым

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/isEmpty.ts
> +    if (Array.isArray(arg) && arg.length === 0) return true;
вместо arg.length === 0 можно !arg.length

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/isEmpty.ts
> +}
Я думаю стоит всегда использовать блоки с {} даже для 1строчных выражений

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/validator/types.ts
> +export type ValidationMethod = (val: string, arg?: number) => boolean;
Опять же экспорты. Если файл не является модулем(нет импортов экспортов) типы видны глобально в проекте

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/validator/validator.ts
> +export default function validator(params: ValidatorParams): ReturnType<typeof validate> {
а зачем разбивать строку, если изначально можно объект задать?

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/validator/validator.ts
> +function validate(validatorConfig: ValidatorConfig): (userData: ValidatorUserData) => ValidatorResult {
Тут по идее можно не писать возвращаемый тип, возвращаемый тип определится автоматом

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/validator/validator.ts
> +            const validationResult = [];
А если поле пустое, оно будет выкидывать сразу все ошибки? Ведь проперка на пустое поле выполняется и в остальных чекерах

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/validator/validator.ts
> +};
Я предлагаю всегда выносить типы

2020-11-05 13:09 UTC, art4vm commented on app/src/utils/validator/errorText.ts
> +    ru: string;
можно будет обсудить локализацию. Обычно эту тему выносят из кода

2020-11-05 13:21 UTC, FellonOne commented on app/src/utils/validator/types.ts
> +export type ValidationMethod = (val: string, arg?: number) => boolean;
Надо будет попробовать. Почитаю про это. Просто никогда не юзал. 
Это считается Best Practice? многие ли компании такое используют?

2020-11-05 13:22 UTC, FellonOne commented on app/src/utils/validator/errorText.ts
> +    ru: string;
Скорее да, поэтому сделал пока отдельной функцией. Пусть пока будет так, потом подумаем

2020-11-05 13:22 UTC, FellonOne commented on app/src/utils/validator/validator.ts
> +};
Да, надо их вынести

2020-11-05 13:24 UTC, FellonOne commented on app/src/utils/validator/validator.ts
> +            const validationResult = [];
Нет, будет выведенеа первая ошибка в порядке функций-валидаторов
тип, если будет строка: "required|max-length: 10|....", а строка пустая, то будет онли одна ошибка

2020-11-05 13:25 UTC, FellonOne commented on app/src/utils/validator/validator.ts
> +export default function validator(params: ValidatorParams): ReturnType<typeof validate> {
Такой тип валидации используется в Laravel :) 
Вспомнил что-то его, и решил такой вот формат использовать, вроде Ларавель любят, а значит и формат должен зайти

2020-11-05 13:26 UTC, FellonOne commented on app/src/utils/isEmpty.ts
> +}
Ну тут уже вкусовщина на самом деле. Такое настраивается в prettier. Можно всегда заставить ставить {}

2020-11-05 15:17 UTC, art4vm commented on app/src/utils/validator/validator.ts
> +            const validationResult = [];
Тогда зачем массив `validationResult`? да и цикл `validatorConfig[fieldName].forEach` не останавлевается на 1й ошибке

2020-11-05 15:21 UTC, art4vm commented on app/src/utils/validator/validator.ts
> +export default function validator(params: ValidatorParams): ReturnType<typeof validate> {
Ну формат может и нормальный, но ты создаешь строку, а потом ее парсишь, зачем?=) Обычно параметры вешаются на поле, а при валидации проверяются, например есть стандартные поля инпутов, которых для валидации вполне хватает

2020-11-09 23:38 UTC, jarith commented on app/src/utils/isEmpty.ts
> +export default function isEmpty(arg: unknown): boolean {
1. Если это полный аналог лодашевского `isEmpty`, то функция некорректно работает для 0 (ожидается true, вместо false сейчас)
2. В целом можно чуть упростить: отдельно обрабатываем `null`, объекты и массивы, для примитивных типов сработает просто приведение к boolean

```Typescript
if (arg === null) {
  return true;
}

if (typeof arg === 'object') {
  return !Object.keys(arg).length;
}

if (Array.isArray(arg)) {
  return !arg.length;
}

return !arg;

2020-11-09 23:38 UTC, jarith commented on app/src/utils/validator/errorText.ts
> +export default function getText(fieldName: string, arg?: string): string {
У `fieldName` слишком общий тип - можно передать любую строку. Обычно объявляют объект с возможными значениями поля и на его основе объявляют тип. Что-то вроде такого:

```Typescript
const FIELD_NAMES = {
 required: 'required',
 minLength: 'min-length',
 ...
} as const;

type FieldName = typeof FIELD_NAMES[keyof typeof FIELD_NAMES]; // получим тип 'required' | 'min-length' | ...
```

2020-11-09 23:38 UTC, jarith commented on app/src/utils/validator/errorText.ts
> +        case 'required':
Соответственно тут можно использовать `FIELD_NAMES`

```suggestion
        case FIELD_NAMES.required:
```

2020-11-09 23:38 UTC, jarith commented on app/src/utils/validator/errorText.ts
> +        default:
`default` можно будет убрать, поскольку TS не позволит передать неверное значение

2020-11-09 23:38 UTC, jarith commented on app/src/utils/validator/functions/isEmail.ts
> +    return val.includes('@');
Если оставляем кастомную валидацию, то лучше нагуглить регулярку для проверки почты и использовать ее

2020-11-09 23:38 UTC, jarith commented on app/src/utils/validator/functions/maxLength.ts
> +    return val.length <= length;
```suggestion
    return !isEmpty(val) && val.length <= length;
```

2020-11-09 23:38 UTC, jarith commented on app/src/utils/validator/types.ts
> +        [fieldName: string]: string;
```suggestion
        [fieldName: FieldName]: string;
```

2020-11-09 23:38 UTC, jarith commented on app/src/utils/validator/types.ts
> +    [fieldName: string]: {func: ValidationMethod; funcName: string; arg: (number & string) | null}[];
1. Для сложных типов лучше использовать `Array<>`. Квадратные скобки в конце строки еле заметны
2. `number & string` в результате дадут тип `never`, поскольку аргумент не может одновременно быть и строкой и числом
3. Тут скорее подразумевается, что arg - опциональный аргумент, поэтому `arg?: ...` вместо `null`

2020-11-09 23:38 UTC, jarith commented on app/src/utils/validator/validator.ts
> +        for (const fieldName of Object.keys(userData)) {
```suggestion
        for (const [name, value] of Object.entries(userData)) {
```

2020-11-09 23:38 UTC, Jarith commented on app/src/utils/validator/validator.ts
> +import {ValidatorResult, ValidatorParams, ValidationMethods, ValidatorConfig, ValidatorUserData} from './types';
```suggestion
import type {ValidatorResult, ValidatorParams, ValidationMethods, ValidatorConfig, ValidatorUserData} from './types';
```

2020-11-09 23:38 UTC, Jarith commented on app/src/utils/validator/validator.ts
> +export default function validator(params: ValidatorParams): ReturnType<typeof validate> {
Тоже не вижу смысла передавать параметры строкой. Помимо того, что ее нужно еще распарсить, можно легко ошибиться с названием валидации

2020-11-09 23:38 UTC, Jarith commented on app/src/utils/validator/validator.ts
> +            }
Можно записать более декларативно

```suggestion
            const config = validatorConfig[fieldName].find(({func, arg}) => !func(value, arg));
            
            if (config) {
                result.wasError = true;
                result.errors[name] = getText(config.funcName, config.arg);
            }
```

2020-11-10 12:42 UTC, art4vm commented on app/src/utils/validator/functions/isEmail.ts
> +    return val.includes('@');
Думаю стоит сделать отдельную функцию валидации на формат поля по примеру поля `pattern` у инпутов. Email это всего лишь один из возможных форматов
А регулярка примерно такая `"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)*$"`

2020-11-13 15:06 UTC, closed without merging

2020-11-13 15:07 UTC, Jarith commented
Договорились использовать formik и yup для валидации, PR неактуален