Feature/feature 54 character move
PraktikumSeoulDevTeam/castleofghosts pull request #53
Opened 2020-12-20 09:51 UTC by kdeit

1-я итерация по задаче №54
Реализация игрового цикла
Проверка лимита движения персонажа

2021-01-09 14:43 UTC, FellonOne approved these changes

2021-01-09 23:07 UTC, art4vm requested changes
Требуется rebase

2021-01-09 23:07 UTC, art4vm commented on app/src/core/engine.ts
> +};
В engine не должно быть состояния. Для этого есть файлы *.canvas

2021-01-09 23:07 UTC, art4vm commented on app/src/core/engine.ts
> +    gameSetStateAction('GAME');
play вызывается при установке состояния GAME, но не наоборот. Зачем тут это необходимо? Этот метод возвращает статичный объект, который никуда не уходит

2021-01-09 23:07 UTC, art4vm commented on app/src/core/engine.ts
> +    return gameSetStateAction('PAUSE');
аналогично play

2021-01-09 23:07 UTC, art4vm commented on app/src/core/engine.ts
> +let gameState: GameStatePoint = 'OFF';
аналогично play

2021-01-09 23:07 UTC, art4vm commented on app/src/core/engine.ts
> +    }
При выходе из состояния GAME, можно останавливать цикл.  requestAnimationFrame возвращает id для этого

2021-01-09 23:07 UTC, art4vm commented on app/src/core/engine.ts
> +};
эти параметры есть в canvas файлах. Вычисляются как height или width / GRID

2021-01-11 13:27 UTC, kdeit commented on app/src/core/engine.ts
> +};
Почему в engine не должно быть состояния?
Идея в том, что канвас занимается отрисовкой слоёв: персонажа, приведения, тумана...
Движок занимается циклом и проверками, хранит состояния. 

Положение персонажа необходимо будет учитывать, например: в слое с туманом. 
Если состояние персонажа храним в main.canvas.ts, то в движке придётся импортировать это состояние и потом прокидывать в туман или сразу импортировать в туман (увеличивая связанность).

Или привидения. Придётся в движке  импортировать положение призрака, импортировать положение персонажа, сравнивать.... 

Я и предлагаю состояние хранить в движке, а канвасы пусть отрисовкой занимаются.

2021-01-11 13:29 UTC, kdeit commented on app/src/core/engine.ts
> +let gameState: GameStatePoint = 'OFF';
Выше были 2 метода, которые стейт меняли неправильно. Тут что не так? Подписались на стейт через мидлваре и в цикле смотрим GAME или не GAME

2021-01-11 13:30 UTC, kdeit commented on app/src/core/engine.ts
> +};
См. коммент выше. Это всё про перенос стейта в engine, что-бы канвас занимался исключительно отрисовкой

2021-01-13 17:20 UTC, art4vm approved these changes
Есть артефакты от старого когда. Остальное без ревью

2021-01-14 03:20 UTC, FellonOne approved these changes

2021-01-14 06:15 UTC, merged