Feature/map model
PraktikumSeoulDevTeam/castleofghosts pull request #55
Opened 2021-01-03 07:26 UTC by FellonOne

release map model and map drawer;
extremely many changes;

2021-01-04 10:55 UTC, kdeit approved these changes
Я бы заапрувил и пошёл дальше. Критичного нет. А мелочи отрефакторить можно в процессе.

2021-01-04 10:55 UTC, kdeit commented on app/src/components/Menu/Menu.tsx
> +    generateLevel: levelGenerateAction
Похоже на артефакт старого кода

2021-01-04 10:55 UTC, kdeit commented on app/src/pages/StartPage/StartPage.tsx
> +    generateMap: levelRandomGenerateAction
А вот тут может логику запуска генератора карты перенести в сагу и пускать когда меняется стейт игры? И всё в одном месте будет.

2021-01-04 10:55 UTC, kdeit commented on app/src/store/Game/sagas.ts
> +            const state: AppStoreState = yield select();
Тут можно взять часть state'а

2021-01-04 10:55 UTC, kdeit commented on app/src/services/LevelGenerator/LevelGenerator.ts
> +import cloneDepp from 'lodash/cloneDeep';
Ошибка в названии :) cloneDeep

2021-01-04 10:55 UTC, kdeit commented on app/src/pages/LevelGenerator/LevelGenerator.tsx
> +                    onClick={() => {
Очень сложно воспринимается. Может в отдельную функцию?

2021-01-04 10:55 UTC, kdeit commented on app/src/pages/LevelGenerator/LevelGenerator.tsx
> +                            key={`${cell}_${Date.now()}_${Math.round(Math.random() * 99999)}_${Date.now()}_${Math.round(
Выглядит устрашающе :)

2021-01-04 12:44 UTC, FellonOne commented on app/src/pages/LevelGenerator/LevelGenerator.tsx
> +                    onClick={() => {
Да, это надо будет вообще удалить (файл LevelGenerator и его упоминания)

2021-01-04 12:45 UTC, FellonOne commented on app/src/pages/StartPage/StartPage.tsx
> +    generateMap: levelRandomGenerateAction
Да, это чисто ради демонстрации 
Надо будет перенести в interlude

2021-01-05 21:19 UTC, art4vm requested changes

2021-01-05 21:19 UTC, art4vm commented on app/src/core/sprites/map/types.ts
> +}
В таких типах нет необходимости, они дублируют сам объект

2021-01-05 21:19 UTC, art4vm commented on app/src/store/Game/reducer.ts
> +// TODO mock
это не мок

2021-01-05 21:19 UTC, art4vm commented on app/src/router/AppRouter/AppRouter.tsx
> - */
зачем это удаление в этом пр?

2021-01-05 21:19 UTC, art4vm commented on app/src/core/main.canvas.ts
> +        });
Это было вынесено в engine, похоже на код от старого патча

2021-01-05 21:19 UTC, art4vm commented on app/src/core/bg.canvas.ts
> +import {BackgroundMap} from '~/store/Level/types';
type

2021-01-05 21:19 UTC, art4vm commented on app/src/core/types.ts
>  }
Если Sprite был вынесен, наверное тут его нужно удалить

2021-01-05 21:19 UTC, art4vm commented on app/src/core/main.canvas.ts
>  }
очистка была сюда перенесена не просто так, кажется это остаток от какого-то старого кода

2021-01-05 21:19 UTC, art4vm commented on app/src/core/bg.canvas.ts
> +import {wallSprites} from './sprites/map/wall';
в пр много изменений связанных с изменением вложенности, предлагаю вернуть как было, тк смысловой нагрузки в этом нет

2021-01-05 21:19 UTC, art4vm commented on app/src/core/sprites/map/wall.ts
> +const SPRITES: AssetMap = {
тип тут не нужен

2021-01-05 21:19 UTC, art4vm commented on app/src/services/LevelGenerator/__levels.ts
> +}
смущает название. А не default как-то иначе будет выглядеть? Так же тип стоит вынести в файл с типами

2021-01-05 21:19 UTC, art4vm commented on app/src/store/Level/actions.ts
> +}
2 экшена с одинаковыми типами, кажется так не стоит делать

2021-01-05 21:19 UTC, art4vm commented on app/src/store/Level/actions.ts
> +import {LEVEL_ACTION_TYPES} from './types';
тут импорт из одного и того же файла, нужно объединить

2021-01-05 21:19 UTC, art4vm commented on app/src/store/Level/actions.ts
> +import {GeneratorConfiguration} from '~/services/LevelGenerator/types';
type

2021-01-05 21:19 UTC, art4vm commented on app/src/store/Level/sagas.ts
> +import {LevelGenerator} from '../../services/LevelGenerator/LevelGenerator';
```suggestion
import {LevelGenerator} from '~/services/LevelGenerator/LevelGenerator';
```

2021-01-05 21:19 UTC, art4vm commented on app/src/store/Level/types.ts
> +import {Floor, Wall} from '../../core/sprites/map';
```suggestion
import {Floor, Wall} from '~/core/sprites/map';
```

2021-01-05 21:19 UTC, art4vm commented on app/src/store/Level/types.ts
> +import {GeneratorConfiguration} from '../../services/LevelGenerator/types';
```suggestion
import {GeneratorConfiguration} from '~/services/LevelGenerator/types';
```

2021-01-05 21:19 UTC, art4vm commented on app/src/store/types.ts
> +import {ToasterState} from './Toaster/types';
```suggestion
import type {LevelState} from './Level/types';
import type {ToasterState} from './Toaster/types';
```

2021-01-05 21:19 UTC, art4vm commented on app/src/store/Level/types.ts
> +    asset: BackgroundAsset | null;
```suggestion
    asset?: BackgroundAsset;
```

2021-01-05 21:19 UTC, art4vm commented on app/src/services/LevelGenerator/__levels.ts
> +import {BackgroundMap} from '../../store/Level/types';
```suggestion
import {BackgroundMap} from '~/store/Level/types';
```

2021-01-05 21:19 UTC, art4vm commented on app/src/services/LevelGenerator/utils.ts
> +export const randSort = (array: number[][]): number[][] => {
тут array это просто одномерный массив

2021-01-05 21:19 UTC, art4vm commented on app/src/core/sprites/map/wall.ts
> +        y: 24
В этом нет смысла, тк не используется

2021-01-05 21:19 UTC, art4vm commented on app/src/services/LevelGenerator/LevelGenerator.ts
> +    const level = cloneDeep(inputLevel);
Тут нет смысла копировать, тк весь массив все равно перезаписывается. Так же сложно читать код, когда то inputLevel то level используется. В циклах и проверках можно использовать inputLevel

2021-01-05 21:19 UTC, art4vm commented on app/src/services/LevelGenerator/LevelGenerator.ts
> +                    level[i - 1][j - 1] = MapPartials.CORRIDOR_ROAD_3_3;
Вместо
```
MapPartials.CORRIDOR_ROAD_3_3
```
думаю можно сразу ставить 
```
{
    part: 'FLOOR',
    type: 'SINGLE'
}
```

сразу сократиться куча кода а так же необходимость в 2 циклах

2021-01-05 21:19 UTC, art4vm commented on app/src/services/LevelGenerator/__levels.ts
> +        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
Предлагаю как-то решить проблему с крайними полями, тк выглядит костыльно да и игровой поле сокращается

2021-01-06 04:51 UTC, FellonOne commented on app/src/router/AppRouter/AppRouter.tsx
> - */
Видимо при мердже затерлось

2021-01-06 04:53 UTC, FellonOne commented on app/src/services/LevelGenerator/__levels.ts
> +        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
Почему выглядит костыльно? Красивый периметр получается
Можно оставить точку *входа* в локацию, оставив дыру в мериметре и все

2021-01-06 05:27 UTC, FellonOne commented on app/src/core/sprites/map/types.ts
> +}
Они используются в коде
В месте:
`export type BackgroundAsset = {part: 'FLOOR' | 'WALL'; type: keyof Floor | keyof Wall};`

2021-01-06 05:27 UTC, FellonOne commented on app/src/store/Game/reducer.ts
> +// TODO mock
да, видимо при мердже косяк(

2021-01-06 05:27 UTC, FellonOne commented on app/src/core/main.canvas.ts
> +        });
Тоже самое, мердж

2021-01-06 05:29 UTC, FellonOne commented on app/src/services/LevelGenerator/__levels.ts
> +}
Это мок хранения уровней

2021-01-06 05:29 UTC, FellonOne commented on app/src/store/Level/actions.ts
> +import {LEVEL_ACTION_TYPES} from './types';
В одном случае - импортируем только типы
Во втором - Enum объект

2021-01-06 19:22 UTC, FellonOne commented on app/src/services/LevelGenerator/LevelGenerator.ts
> +    const level = cloneDeep(inputLevel);
Нет, к сожалению нужно
Для построения стен используется первичная информация об уровне 0 и 1
Т.е. если сразу делать внутри inputLevel, то там будут уже изменения и алгоритм не будет работать

А вот для дорог внутри замка нужна инфа по уже построенным дорогам
Чтоб не строить лишнии

2021-01-06 19:26 UTC, FellonOne commented on app/src/services/LevelGenerator/LevelGenerator.ts
> +                    level[i - 1][j - 1] = MapPartials.CORRIDOR_ROAD_3_3;
это расширение для будущих изменений
тип, на MapPartials структуре раскрашивать уровни в разные цвета, заполнения всякими фичами и тд

2021-01-09 23:11 UTC, art4vm commented on app/src/store/Game/sagas.ts
> +            yield call(drawMap.bind(null, map));
```suggestion
            yield call(drawMap, map);
```

2021-01-09 23:11 UTC, art4vm commented on app/src/core/sprites/map/types.ts
> +}
Я видел где это используется
```ts
export type BackgroundAsset = {type: 'FLOOR'; part: keyof typeof floorSprites} | {type: 'WALL'; part: keyof typeof wallSprites}
```

2021-01-11 02:43 UTC, Jarith approved these changes

2021-01-12 11:44 UTC, art4vm approved these changes

2021-01-12 11:45 UTC, merged

2021-01-12 11:48 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализация рендера карты на слое canvasBG](https://trello.com/c/xJyGvupe/61-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D1%80%D0%B5%D0%BD%D0%B4%D0%B5%D1%80%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D1%8B-%D0%BD%D0%B0-%D1%81%D0%BB%D0%BE%D0%B5-canvasbg)