feature/full-screen-api
PraktikumSeoulDevTeam/castleofghosts pull request #56
Opened 2021-01-04 16:34 UTC by FellonOne

implements Full Screen API;
add enable/disable fullscreen by button (default: F);

2021-01-11 02:42 UTC, Jarith requested changes
Код заведется только в хроме из-за необходимости вендроских префиксов в следующих случаях:

`fullscreenElement`
`mozFullScreenElement`
`webkitFullscreenElement`
`msFullscreenElement`

`requestFullscreen()`
`msRequestFullscreen()`
`mozRequestFullScreen()`
`webkitRequestFullscreen()`

Так что нужно сначала проверить наличие соответствующего метода перед его запуском

`exitFullscreen()`
`msExitFullscreen()`
`mozCancelFullScreen()`
`webkitExitFullscreen()`

2021-01-11 16:55 UTC, art4vm reviewed
Вендорские преффиксы на текущий момент нужны только для сафари и оперы (оба `webkit`), остальные работают по стандарту

2021-01-11 16:55 UTC, art4vm commented on app/src/webApi/fullScreen.ts
> +export class FullScreenApi {
class тут не нужен, es6 модули являются синглтонами

2021-01-15 06:30 UTC, Jarith approved these changes

2021-01-15 06:38 UTC, kdeit approved these changes

2021-01-15 06:42 UTC, merged

2021-01-15 21:24 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Full Screen API](https://trello.com/c/GrYgpqQ0/82-full-screen-api)