Feature/feature 89 key
PraktikumSeoulDevTeam/castleofghosts pull request #70
Opened 2021-01-16 13:59 UTC by kdeit

На карте есть ключ.
Нашёл — открылась дверь.
Вошёл в дверь — статус «WIN»

2021-01-16 14:37 UTC, art4vm requested changes
Поля вроде completeMap вообще не из формата levelGenerator и не используются им. Их вообще нужно удалить. Если решили использовать поля вроде startPoint endPoint, то и нужно их использовать. В тч добавить подобное поле и для ключа.

2021-01-16 15:14 UTC, art4vm commented
Добавил поле keyPoint в свой пр. Достаточно проверять конкретные координаты, а не перебирать массив

2021-01-17 12:16 UTC, FellonOne approved these changes

2021-01-18 06:13 UTC, FellonOne approved these changes

2021-01-18 06:59 UTC, Jarith approved these changes

2021-01-18 11:20 UTC, art4vm approved these changes

2021-01-18 11:20 UTC, merged

2021-01-18 11:37 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ключи на карте](https://trello.com/c/hhQKsFEY/89-%D0%BA%D0%BB%D1%8E%D1%87%D0%B8-%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B5)