feature/win-end-screen
PraktikumSeoulDevTeam/castleofghosts pull request #73
Opened 2021-01-19 09:35 UTC by FellonOne

add win/end screen;
add several level on one game;
fix issues in __levels;

2021-01-19 13:06 UTC, kdeit requested changes
Есть какой-то баг.
Начал уровень - Пишет 1/4
Попался призраку - Try Again - Пишет 1/3
Прошёл - Пишет 1/2
Потом попался — Опять 1/3

2021-01-19 13:09 UTC, art4vm commented on app/src/store/Game/reducer.ts
> +        }
В этом нет необходимости, можно ставить ко-во уровней в SET_LEVELS_ORDER.
При выполнении SET_LEVELS_ORDER уже устанавливается массив уровней и он **всегда** будет равен countLevels. А еще лучше убрать счетчик из этого хранилища и добавить его в хранилище levels(обновляется при добавлении уровней) тк это значение всегда будет одинаковым для всех игр

2021-01-19 13:09 UTC, art4vm commented on app/src/store/Game/reducer.ts
> +            if (action.payload !== undefined) {
в этом не необходимости

2021-01-19 13:09 UTC, art4vm commented on app/src/store/Game/sagas.ts
> +                );
зачем рандомизировать длину игры? В таком случае нет смысла считать очки, тк они будут примерно пропорциональны кол-ву уровней

2021-01-19 13:49 UTC, FellonOne commented
> Есть какой-то баг.
> Начал уровень - Пишет 1/4
> Попался призраку - Try Again - Пишет 1/3
> Прошёл - Пишет 1/2
> Потом попался — Опять 1/3

Это все из-за рандомизации кол-ва уровней

2021-01-19 13:49 UTC, FellonOne commented on app/src/store/Game/reducer.ts
> +            if (action.payload !== undefined) {
есть, когда меняешть на значение 0, оно не попадает в ветвь и не меняется

2021-01-19 13:50 UTC, FellonOne commented on app/src/store/Game/sagas.ts
> +                );
в теории да(
Обсудим вечером тогда. Можно зафиксировать на 3-4 уровня за игру

2021-01-19 13:55 UTC, art4vm commented on app/src/store/Game/reducer.ts
> +            if (action.payload !== undefined) {
Предполагается, что явно передавать уровень не нужно, все ставится автоматом в sagas в стадии interlude

2021-01-21 19:08 UTC, art4vm approved these changes

2021-01-21 19:09 UTC, art4vm commented
В рамках своего ПР с leaderboard сделаю еще правки

2021-01-21 19:13 UTC, kdeit approved these changes

2021-01-21 20:53 UTC, merged

2021-01-21 21:40 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Смена уровня](https://trello.com/c/Kfi0Z2gn/86-%D1%81%D0%BC%D0%B5%D0%BD%D0%B0-%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D1%8F)