Исправления в сервисе геолокации
PraktikumSeoulDevTeam/castleofghosts pull request #76
Opened 2021-01-22 21:22 UTC by art4vm

Исправлены ошибки с типами
Немного отрефакторен сервис и хранилище

2021-01-23 14:28 UTC, kdeit requested changes
Не вижу в ПР смысла.
Хотелось бы понять в чём были допущены такие-уж ошибки.
Сейчас больше похоже, что просто переписал как удобно.

2021-01-23 14:35 UTC, art4vm commented
> Не вижу в ПР смысла.
А я вижу.

> Хотелось бы понять в чём были допущены такие-уж ошибки.
Достаточно открыть код и увидеть ошибки

> Сейчас больше похоже, что просто переписал как удобно.
Удобно для чего?

2021-01-28 05:41 UTC, FellonOne approved these changes

2021-02-01 14:41 UTC, kdeit approved these changes

2021-02-12 19:46 UTC, merged