Feature/feature 84 perfomance api
PraktikumSeoulDevTeam/castleofghosts pull request #78
Opened 2021-01-26 14:18 UTC by kdeit

#84 Performance API
На каждый запрос к API навешена метрика.
Если ответ более указанного времени => пишем в лог на сервере.

Для тестирования необходимо изменить DURATION_LIMIT в perfomance.ts
Сейчас стоит 10 секунд.

2021-01-28 05:41 UTC, FellonOne reviewed
Ждем тогда патч с метрикой яндекса и уже делаем ревью

2021-02-01 19:50 UTC, kdeit commented
Вместо записи в лог шлём данные в Яндекс.Метрику

2021-02-12 11:24 UTC, FellonOne requested changes

2021-02-12 11:24 UTC, FellonOne commented on app/src/services/perfomance/perfomance.ts
> +    Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
Можно подключить uuid библиотеку, для генерации рандомных id
Знаю по практике,  что повторения будут при 10к итерациях (даже несколько повторений!)
Тип, Math.random() в JS абсолютно не криптостойкая и рандом там очень условный

Это так, если руки решат дойти) 
В данном случае и такой рандом сойдет

2021-02-12 11:24 UTC, FellonOne commented on server/src/server.ts
> +server.use(bodyParser.json());
Боди парсер не нужен в Экспрессе, уже как несколько лет, он идет из коробки
Раньше его не было, и все юзали боди-парсер, потом комьюнити экспресса решило добавить данный функционал в свою коробку)

```
// Parse JSON bodies for this app. Make sure you put
// `app.use(express.json())` **before** your route handlers!
app.use(express.json());
```

Вот тут есть описание: 
https://masteringjs.io/tutorials/express/body

2021-02-12 21:07 UTC, art4vm requested changes

2021-02-12 21:07 UTC, art4vm commented on package.json
> +    "body-parser": "^1.19.0",
```suggestion
    "body-parser": "1.19.0",
```

2021-02-12 21:07 UTC, art4vm commented on app/www/index.html
> +        <!-- /Yandex.Metrika counter -->
Не корректно в статик файл добавлять код, для этого в webpack есть плагин. Думаю можно добавить еще один entrypoint с кодом для метрики

2021-02-12 21:07 UTC, art4vm commented on app/src/services/perfomance/perfomance.ts
> +    Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
Тут вообще не нужен хэш тк данные не используется между рантаймами тд. Достаточно просто каунтера, это будет гарантировать уникальность

2021-02-12 21:07 UTC, art4vm commented on app/src/api/index.ts
> +    request.hash = performanceCheckStart(request.url);
В данном случае можно обойтись стандартными средствами и не перекрывать типы axios. В конфиге есть специальное поле adapter в которое можно передать кастомный адаптер, в котором выполнять необходимые действия. Ну или еще проще, добавить кастомный header, например X-perf и использовать его для передачи хэша

2021-02-12 21:07 UTC, art4vm commented on app/src/api/types.ts
> +}
Вот прям сильно считаю что перекрывать конфиги сторонней библиотеки не стоит, тем более в этом нет необходимости

2021-02-12 21:07 UTC, art4vm commented on .gitignore
> +logs/*
```suggestion
logs/*

```

2021-02-14 07:18 UTC, FellonOne approved these changes

2021-02-14 09:54 UTC, art4vm approved these changes

2021-02-14 09:55 UTC, merged

2021-02-14 09:59 UTC, art4vm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Performance API](https://trello.com/c/mDtFnTEm/84-performance-api)