features/authorization-registration-forms
PraktikumSeoulDevTeam/castleofghosts pull request #9
Opened 2020-11-17 07:50 UTC by FellonOne

- add authorization and registration forms;

2020-11-17 11:08 UTC, art4vm commented on app/src/assets/scss/_authentication.scss
> +    min-height: auto !important;
лучше избегать таких переопределений

2020-11-17 11:08 UTC, art4vm commented on app/src/assets/scss/_authentication.scss
> +}
Параметры цвета в css наследуются. Зачем их определять в каждом элементе?
Желательно вынести в переменные цвета и размера шрифта
Предлагаю размер шрифта указывать в em
Для отступов есть миксины и классы

Возможно стоит это делать отдельным патчем

2020-11-17 11:08 UTC, art4vm commented on app/src/components/FormControl/FormControl.scss
> +}
Про цвета, отступы и шрифты см предыдущий коммент

2020-11-17 11:08 UTC, art4vm commented on app/src/components/FormControl/FormControl.tsx
> +    });
Больше похоже, что стиль input-container сам является блоком

2020-11-17 11:08 UTC, art4vm commented on app/src/components/FormControl/FormControl.tsx
> +    }, {});
поля не всегда могуть быть пустыми изначально, например при изменении параметров пользователя

2020-11-17 11:08 UTC, art4vm commented on app/src/pages/Authorization/Authorization.tsx
> +import {Button} from '../../components/Button';
сам же вроде предлагал использовать index.ts в /components  и импортировать из него

2020-11-17 11:08 UTC, art4vm commented on package.json
> +    "formik": "^2.2.5",
Тут и ниже нужно залочить версию

2020-11-17 11:08 UTC, art4vm commented on app/src/pages/Authorization/Authorization.scss
> +}
См предыдущие комменты по стилям

2020-11-17 11:08 UTC, art4vm commented on app/src/pages/Authorization/Authorization.tsx
> +                        console.log(formData);
нужные действия уже есть, тч думаю стоит сразу впилить сюда вызов авторизации

2020-11-17 11:08 UTC, art4vm commented on app/src/pages/Registration/Registration.tsx
> +                    onSubmit={(formData) => {
так же как и с авторизацией. Только нужно добавить обработку в sagas.ts

2020-11-17 11:10 UTC, art4vm commented on app/src/components/FormControl/FormControl.tsx
> +        <div className="form-block__input-container" key={fieldName} style={{color: 'white'}}>
input-container выглядит как отдельный контейнер, тем более инпут может быть вне формы

2020-11-17 11:15 UTC, art4vm commented on app/src/pages/Registration/Registration.tsx
> +});
Нужны валидаторы на формат поля

2020-11-17 12:04 UTC, FellonOne commented on app/src/pages/Authorization/Authorization.tsx
> +import {Button} from '../../components/Button';
Увидел в каком-то патче, что удалили index.ts у Button
Подумал, что отказались и не стал добавлять

2020-11-17 12:05 UTC, FellonOne commented on app/src/pages/Authorization/Authorization.tsx
> +                        console.log(formData);
Думал добавить привязку к сагам следующим пулл-реквестом
Там как раз есть задачи на сервис Авторизации/Регистрации

+ в след пулл реквесте связать данные страницы друг с другом (добавить роутинг регистрация <=> авторизация) и тд

2020-11-17 12:06 UTC, FellonOne commented on app/src/pages/Registration/Registration.tsx
> +});
Имелось ввиду на формат телефона?

2020-11-17 12:33 UTC, art4vm commented on app/src/components/FormControl/FormControl.tsx
> +            </div>
У формика есть компонент ErrorMessage, он тут не подходит?

2020-11-17 15:55 UTC, art4vm commented on package.json
> +    "formik": "^2.2.5",
А чего сам formik не залочил 😃

2020-11-17 15:55 UTC, art4vm commented on app/src/pages/Registration/Registration.tsx
> +                    onSubmit={(formData) => {
обработчик в sagas уже добавил

2020-11-17 15:55 UTC, art4vm commented on app/src/pages/Authorization/Authorization.tsx
> +                        console.log(formData);
тут к сагам не нужно ничего привязывать, нужно подключить redux через react-redux и вызвать action в который в виде **объекта** передать поля.

2020-11-17 15:55 UTC, art4vm commented on app/src/pages/Authorization/Authorization.tsx
> +import {Button} from '../../components/Button';
Я удалил, тк он перестал быть нужен, но Index который в корне каталога components остался

2020-11-17 15:55 UTC, art4vm commented on app/src/pages/Registration/Registration.tsx
> +    phoneNumber: Yup.string().phone('*', false, 'phone number is not valid').required('field must be required'),
а по какому формату он проверяет телефон?
я имел ввиду проверку всех полей по заданному формату, где просто regexp задаешь. Кроме телефона есть еще и email, да и пароль и логин принято проверять на допустимые символы

2020-11-17 21:07 UTC, kdeit commented on app/src/assets/scss/_authentication.scss
> +        font-size: 16px;
Посмотри миксины для типографики. Я бы предложил их использовать.
Т.е. в них определить все начертания текста в проекте и всё, что касается текста писать через миксины.
Очень часто после вёрстки дизайнер смотрит и говорит «Неее. Надо, конечно, этот текст поменьше сделать» и что-б по проекту не искать в миксине поменять и всё.
+ наглядно видишь все начертания. А их много лучше не использовать (иначе зоопарк).

2020-11-17 21:07 UTC, kdeit commented on app/src/assets/scss/_authentication.scss
> +    min-height: auto !important;
Где-то прочитал правило (и взял его за стандарт), что использование !important = явный фэйл.
Особо критичные товарищи говорят, что если ты что-то где-то переопределяешь (не только через important), то это также фейл. Но это через чур радикально.

2020-11-17 21:07 UTC, kdeit commented on app/src/components/button/Button.tsx
> +    submit: false
button type еще может быть reset. Так что тут boolean не корректен имхо

2020-11-17 21:07 UTC, kdeit commented on app/src/pages/Registration/Registration.tsx
> +                <h4 className="t-title authentication__title">
Если это первый заголовок на странице, то семантически правильно `<h1>` и далее по вложенности.
А то ещё прибежит СЕО-шник и будет бомбить :)

2020-11-19 07:10 UTC, Jarith requested changes

2020-11-19 07:10 UTC, jarith commented on app/src/pages/Authorization/Authorization.tsx
> +                <h4 className="t-title authentication__title">
`<h1>` больше подойдет, т. к. это главный заголовок страницы

2020-11-19 07:10 UTC, jarith commented on app/src/pages/Authorization/Authorization.tsx
> +                    <span>Authorization</span>
```suggestion
                    Authorization
```

2020-11-19 07:10 UTC, jarith commented on app/src/pages/Authorization/Authorization.tsx
> +                    }}
Предлагаю не инлайнить этот объект, а объявить отдельно перед компонентом

2020-11-19 07:10 UTC, jarith commented on app/src/pages/Authorization/Authorization.tsx
> +                        <div>Registration</div>
Тут же должна быть ссылка на страницу регистрации? Если так, то ссылкой и нужно сделать

2020-11-19 07:10 UTC, jarith commented on app/src/pages/Registration/Registration.tsx
> +                    }}
Тут прям точно стоит вытащить объект из компонента

2020-11-19 07:10 UTC, jarith commented on app/src/pages/Registration/Registration.tsx
> +                <h4 className="t-title authentication__title">
> Если это первый заголовок

Только не первый, а основной, который описывает содержимое страницы. То есть, если это страница регистрации, то через `<h1>` разумно разметить заголовок "Регистрация" и не важно, первым он идет или последним

2020-11-19 07:10 UTC, Jarith commented on app/src/pages/Registration/Registration.tsx
> +                    onSubmit={(formData) => {
Предлагаю отдельным PR

2020-11-19 07:10 UTC, Jarith commented on app/src/pages/Registration/Registration.tsx
> +                        <div>Authorization</div>
Соответственно, тут надо бы ссылку на страницу авторизации

2020-11-19 08:59 UTC, FellonOne commented on app/src/pages/Registration/Registration.tsx
> +    phoneNumber: Yup.string().phone('*', false, 'phone number is not valid').required('field must be required'),
Формат строка вида 901234567 90 - код оператора 123 45 67  номер
либо +998 (код страны) + то что выше
либо 998 (код страны) + то что выше

Поле email добавил + проверку 
Насчет логина и тд, там вроде как будут допустим любые символы
можно добавить доп проверку по регулярке, но думаю на данном этапа можно пока оставить так

2020-11-19 11:52 UTC, Jarith commented
@FellonOne  Остался коммент про миксины и надо бы конфликты порешать

В остальном все отлично

2020-11-19 13:32 UTC, Jarith approved these changes

2020-11-21 07:01 UTC, closed without merging